### PR TITLE
OPS-2361 Add command diff

### PR DESCRIPTION
**Pull request by alex-harvey-z3q**
This implements a command diff that diffs a running stack's template via
the fetch_remote_template command and the template generated by the stack.

### CODE REVIEW

**Comment by alexharv074** [comment]
# tests

## Given this diff

```diff
--- a/test/templates/test.template.yaml.j2
+++ b/test/templates/test.template.yaml.j2
@@ -23,10 +23,14 @@ Resources:
         - Key: "{{ key }}"
           Value: "{{ value }}"
         {% endfor %}
+        - Key: Foo
+          Value: Bar
       {%- endif %}
 
 Outputs:
   InstanceArn:
     Value: !Ref MyInstance
+  AvailabilityZone:
+    Value: !GetAtt MyInstance.AvailabilityZone
 
 # vim: set ft=yaml:
```

## Using deepdiff (this PR)

The output I receive is:

```
[aws:personal1] /src $ sceptre --dir=test --var-file=/env/common-env.yaml --var-file=/env/test.yaml diff test.yaml 
test-test: Item root['Resources']['MyInstance']['Properties']['InstanceType'] removed from dictionary.
Item root['Resources']['MyInstance']['Properties']['Tags'][6] added to iterable.
```

## Using dictdiffer 

I also tested a second version of this using another library, dictdiffer. For dictdiffer, apply this patch:

```diff
diff --git a/requirements/prod.txt b/requirements/prod.txt
index 60e4f91..ff96df2 100644
--- a/requirements/prod.txt
+++ b/requirements/prod.txt
@@ -5,4 +5,4 @@ Jinja2>=2.8,<3
 networkx==2.1
 PyYaml>=5.1,<6.0
 typing>=3.7,<3.8
-deepdiff==5.5.0
+dictdiffer==0.8.1
diff --git a/sceptre/cli/template.py b/sceptre/cli/template.py
index bc36645..769c946 100644
--- a/sceptre/cli/template.py
+++ b/sceptre/cli/template.py
@@ -118,7 +118,7 @@ def diff_command(ctx, path):
 
     plan = SceptrePlan(context)
     responses = plan.diff()
-    output = "\n".join([": ".join(value) for value in responses.values()])
+    output = [value[0] + ": " + str(value[1]) for value in responses.values()]
     write(output, context.output_format)
 
 
diff --git a/sceptre/plan/actions.py b/sceptre/plan/actions.py
index f781493..e39090b 100644
--- a/sceptre/plan/actions.py
+++ b/sceptre/plan/actions.py
@@ -16,7 +16,7 @@ from datetime import datetime, timedelta
 import botocore
 import json
 import yaml
-import deepdiff
+import dictdiffer
 
 from dateutil.tz import tzutc
 
@@ -614,16 +614,8 @@ class StackActions(object):
         local_template = yaml.load(local_template_stream,
                                    Loader=yaml.BaseLoader)
 
-        deep_diffs = deepdiff.DeepDiff(
-            remote_template, local_template, ignore_order=True
-        )
-
-        if bool(deep_diffs):
-            response = deep_diffs.pretty()
-        else:
-            response = "No diffs"
-
-        return [self.stack.external_name, response]
+        diffs = dictdiffer.diff(remote_template, local_template)
+        return [self.stack.external_name, list(diffs)]
 
     @add_stack_hooks
     def validate(self):
diff --git a/tests/test_actions.py b/tests/test_actions.py
index de70a9f..b2086e0 100644
--- a/tests/test_actions.py
+++ b/tests/test_actions.py
@@ -1021,7 +1021,7 @@ class TestStackActions(object):
         self.template._body = '---\nfoo: bar'
 
         response = self.actions.diff()
-        assert response == [sentinel.external_name, "No diffs"]
+        assert response == [sentinel.external_name, []]
 
     @patch("sceptre.plan.actions.StackActions.fetch_remote_template")
     def test_diff_some_diffs(
@@ -1034,7 +1034,7 @@ class TestStackActions(object):
 
         assert response == [
             sentinel.external_name,
-            "Item root['baz'] added to dictionary."
+            [("add", "", [("baz", "qux")])]
         ]
 
     @patch("sceptre.plan.actions.StackActions.fetch_remote_template")
```

## Output

```
[aws:personal1] /src $ sceptre --dir=test --var-file=/env/common-env.yaml --var-file=/env/test.yaml diff test.yaml 
["test-test: [('add', 'Resources.MyInstance.Properties.Tags', [(6, {'Key': 'Foo', 'Value': 'Bar'})]), ('remove', 'Resources.MyInstance.Properties', [('InstanceType', 'm1.small')])]"]
```

**Comment by alexharv074** [comment]
In [5d55619d26ae09dfa651a71659953aafab3be923](https://github.com/fsa-streamotion/sceptre/pull/5/commits/5d55619d26ae09dfa651a71659953aafab3be923) commit I have suppressed the stack name in the output. This is for consistency with the `fetch-remote-template` command. I experimented with changing the `fetch-remote-template` command to also show the stack name, but realised it is better to be consistent with the `generate` command from upstream.

**Comment by alexharv074** [comment]
Now tested in stacks with multiple stacks in stack groups such as the network stack. Output might look like:

```
[aws:foxsports-gitops-test] /src $ sceptre --dir=network --var-file=/env/common-env.yaml --var-file=/env/network.yaml diff network.yaml 
['No diffs', 'No diffs', "Item root['Resources']['InternetGateway']['Properties']['Tags'][1] added to iterable."]
```

**Comment by alexharv074** [comment]
Further to the above, I think not reporting the stack name in the case of using the difflib library results in output that is unacceptably confusing, meaning that I now lean to not being consistent. So, we would have output like this:

```
[aws:foxsports-gitops-test] /src $ sceptre --dir=network --var-file=/env/common-env.yaml --var-file=/env/network.yaml diff network.yaml 
gitops-test-vpc: 
gitops-test-nacl: 
gitops-test-network: --- remote_template
+++ local_template
@@ -31,6 +31,9 @@
         -
           Key: Name
           Value: !Ref NameTagValue
+        -
+          Key: Foo
+          Value: Bar
 
   InternetGatewayAttachment:
     Type: AWS::EC2::VPCGatewayAttachment
```

As opposed to:

```
[aws:foxsports-gitops-test] /src $ sceptre --dir=network --var-file=/env/common-env.yaml --var-file=/env/network.yaml diff network.yaml 


--- remote_template
+++ local_template
@@ -31,6 +31,9 @@
         -
           Key: Name
           Value: !Ref NameTagValue
+        -
+          Key: Foo
+          Value: Bar
 
   InternetGatewayAttachment:
     Type: AWS::EC2::VPCGatewayAttachment
```

**Comment by mrowlingfox** [comment]
Can you please put all these comments in one cohesive document for the team to review. Confluence is a logical place for this. This should focus on the output of the stack to make it clear what is being changed and make it easy for devs to use.

Once that has been decided then we can begin to review the implementation method.

**Pull request closed without merging**
